apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs-app
        image: 9davidandres9/authentication:1.1.0
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: Development
        readinessProbe:
          httpGet:
            path: /api/hello
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/hello
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10