version: '3.8'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: authentication:1.1.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    command: ["npm", "run" ,"dev"]
